"""history change

Revision ID: 227a617475de
Revises: 656223af0ab9
Create Date: 2023-09-05 21:49:32.942384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '227a617475de'
down_revision = '656223af0ab9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favourite')
    op.drop_column('films', 'genre')
    op.drop_column('films', 'country')
    op.add_column('history', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('history', sa.Column('is_favourite', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'is_favourite')
    op.drop_column('history', 'date')
    op.add_column('films', sa.Column('country', mysql.JSON(), nullable=True))
    op.add_column('films', sa.Column('genre', mysql.JSON(), nullable=True))
    op.create_table('favourite',
    sa.Column('id_favourite', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('request', mysql.VARCHAR(length=250), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='favourite_ibfk_1'),
    sa.PrimaryKeyConstraint('id_favourite'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
