"""After Defense State

Revision ID: 656223af0ab9
Revises: bcc5b7d8354b
Create Date: 2023-07-13 10:19:47.743895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '656223af0ab9'
down_revision = 'bcc5b7d8354b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourite',
    sa.Column('id_favourite', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('request', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id_favourite')
    )
    op.create_table('film_actor',
    sa.Column('id_film_actor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_actor', sa.Integer(), nullable=True),
    sa.Column('id_film', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_actor'], ['actor.id_actor'], ),
    sa.ForeignKeyConstraint(['id_film'], ['films.id_film'], ),
    sa.PrimaryKeyConstraint('id_film_actor')
    )
    op.create_table('film_country',
    sa.Column('id_film_country', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_film', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_film'], ['films.id_film'], ),
    sa.PrimaryKeyConstraint('id_film_country')
    )
    op.create_table('film_genre',
    sa.Column('id_film_genre', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_film', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_film'], ['films.id_film'], ),
    sa.PrimaryKeyConstraint('id_film_genre')
    )
    op.create_table('history',
    sa.Column('id_history', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('request', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id_history')
    )
    op.create_table('parental_control',
    sa.Column('id_parental_control', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_film', sa.Integer(), nullable=True),
    sa.Column('danger', sa.String(length=100), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_film'], ['films.id_film'], ),
    sa.PrimaryKeyConstraint('id_parental_control')
    )
    op.drop_column('actor', 'id_film')
    op.drop_column('films', 'parental_control')
    op.drop_column('films', 'employees')
    op.drop_column('films', 'country')
    op.drop_column('films', 'genre')
    op.drop_column('users', 'history')
    op.drop_column('users', 'favourite')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favourite', mysql.JSON(), nullable=True))
    op.add_column('users', sa.Column('history', mysql.JSON(), nullable=True))
    op.add_column('films', sa.Column('country', mysql.JSON(), nullable=True))
    op.add_column('films', sa.Column('genre', mysql.JSON(), nullable=True))
    op.add_column('films', sa.Column('employees', sa.BLOB(), nullable=True))
    op.add_column('films', sa.Column('parental_control', sa.BLOB(), nullable=True))
    op.add_column('actor', sa.Column('id_film', mysql.JSON(), nullable=True))
    op.drop_table('parental_control')
    op.drop_table('history')
    op.drop_table('film_genre')
    op.drop_table('film_country')
    op.drop_table('film_actor')
    op.drop_table('favourite')
    # ### end Alembic commands ###
