"""Defense state

Revision ID: bcc5b7d8354b
Revises: d30ef48a542b
Create Date: 2023-07-13 07:27:46.184465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc5b7d8354b'
down_revision = 'd30ef48a542b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
