"""initial

Revision ID: d30ef48a542b
Revises: 
Create Date: 2023-07-02 16:46:53.846261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd30ef48a542b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films',
                    sa.Column('id_film',sa.Integer(), nullable=False),
                    sa.Column('name', sa.PickleType, nullable=False),
                    sa.Column('parental_control', sa.String(length=255), nullable=False),
                    sa.Column('country', sa.JSON, nullable=True),
                    sa.Column('genre', sa.JSON, nullable=False),
                    sa.Column('employees', sa.PickleType, nullable=False),
                    sa.PrimaryKeyConstraint('id_film')
                    )
    op.create_table('actor',
                    sa.Column('id_actor', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=250), nullable=True),
                    sa.Column('gender', sa.String(10), nullable=False),
                    sa.Column('birthdate', sa.Date, nullable=False),
                    sa.Column('id_film', sa.JSON, nullable=False),
                    sa.PrimaryKeyConstraint('id_actor')
                    )
    op.create_table('users',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(250), nullable=False),
                    sa.Column('age', sa.Integer, default=0, nullable=False),
                    sa.Column('reg_data', sa.Date, nullable=False),
                    sa.Column('email', sa.String(50), nullable=False),
                    sa.Column('phone', sa.String(20), nullable=False),
                    sa.Column('history', sa.JSON, default=0, nullable=False),
                    sa.Column('favourite', sa.JSON, nullable=False),
                    sa.Column('points', sa.Integer, default=50, nullable=False),
                    sa.Column('role', sa.String(20), default='User', nullable=False),
                    sa.PrimaryKeyConstraint('user_id')
                    )
    op.create_table('logs',
                    sa.Column('log_id', sa.Integer, nullable=False,  autoincrement=True),
                    sa.Column('username', sa.String(250), nullable=False),
                    sa.Column('user_id', sa.Integer, nullable=False),
                    sa.Column('user', sa.Users, backref='logs', nullable=False),
                    sa.Column('message_text', sa.String(1000), nullable=False),
                    sa.Column('message_time', sa.String(100), nullable=False),
                    sa.PrimaryKeyConstraint('log_id'),
                    sa.ForeignKeyConstraint('users.user_id')
                    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('films')
    op.drop_table('actor')
    op.drop_table('users')
    op.drop_table('logs')
    # ### end Alembic commands ###
